// Generated by Governance Pipeline
// Implementation has NO access to original requirements
// Architecture version: v1786079538550

export interface AppEvent {
  name: string;
  payload: unknown;
  timestamp: number;
}

export type EventHandler = (event: AppEvent) => void;

export class EventBus {
  private readonly listeners = new Map<string, EventHandler[]>();

  subscribe(event: string, handler: EventHandler): () => void {
    const handlers = this.listeners.get(event) ?? [];
    handlers.push(handler);
    this.listeners.set(event, handlers);
    return () => {
      const current = this.listeners.get(event);
      if (current === undefined) return;
      const index = current.indexOf(handler);
      if (index >= 0) current.splice(index, 1);
    };
  }

  emit(name: string, payload: unknown = {}): void {
    const event: AppEvent = { name, payload, timestamp: Date.now() };
    for (const handler of this.listeners.get(name) ?? []) {
      handler(event);
    }
  }

  listenerCount(name: string): number {
    return (this.listeners.get(name) ?? []).length;
  }
}

export class IllegalTransitionError extends Error {
  constructor(machine: string, state: string, event: string) {
    super(`State machine "${machine}": no transition from "${state}" on event "${event}"`);
    this.name = 'IllegalTransitionError';
  }
}

export interface TransitionRule {
  from: string;
  to: string;
  on: string;
}

export class StateMachine {
  readonly name: string;
  readonly states: readonly string[];
  readonly transitions: readonly TransitionRule[];
  private currentState: string;

  constructor(name: string, states: string[], initialState: string, transitions: TransitionRule[]) {
    this.name = name;
    this.states = states;
    this.currentState = initialState;
    this.transitions = transitions;
  }

  getState(): string {
    return this.currentState;
  }

  can(event: string): boolean {
    return this.transitions.some(t => t.from === this.currentState && t.on === event);
  }

  transition(event: string): string {
    const rule = this.transitions.find(t => t.from === this.currentState && t.on === event);
    if (rule === undefined) {
      throw new IllegalTransitionError(this.name, this.currentState, event);
    }
    this.currentState = rule.to;
    return this.currentState;
  }
}

export const eventBus = new EventBus();

export function createMachines(): Record<string, StateMachine> {
  return {
    "experience-flow": new StateMachine(
      "experience-flow",
      ["curiosity","discovery","confidence","delight"],
      "curiosity",
      [
    { from: "curiosity", to: "discovery", on: "emotion:curiosity:to:discovery" },
    { from: "discovery", to: "confidence", on: "emotion:discovery:to:confidence" },
    { from: "confidence", to: "delight", on: "emotion:confidence:to:delight" }
      ],
    ),
    "system-status": new StateMachine(
      "system-status",
      ["idle","loading","ready","error"],
      "idle",
      [
    { from: "idle", to: "loading", on: "app:init" },
    { from: "loading", to: "ready", on: "app:loaded" },
    { from: "loading", to: "error", on: "system:loadFailed" },
    { from: "error", to: "loading", on: "system:retry" }
      ],
    ),
    "interaction-phase": new StateMachine(
      "interaction-phase",
      ["passive","attentive","active","transitioning"],
      "passive",
      [
    { from: "passive", to: "attentive", on: "interaction:userApproach" },
    { from: "attentive", to: "active", on: "interaction:userInput" },
    { from: "active", to: "transitioning", on: "interaction:actionComplete" },
    { from: "transitioning", to: "passive", on: "interaction:settle" },
    { from: "transitioning", to: "attentive", on: "interaction:nextInput" }
      ],
    ),
  };
}

export const machines = createMachines();

export function wireDefaultHandlers(): void {
  const fresh = createMachines();
  eventBus.subscribe("emotion:curiosity:to:discovery", () => fresh["experience-flow"].transition("emotion:curiosity:to:discovery"));
  eventBus.subscribe("emotion:discovery:to:confidence", () => fresh["experience-flow"].transition("emotion:discovery:to:confidence"));
  eventBus.subscribe("emotion:confidence:to:delight", () => fresh["experience-flow"].transition("emotion:confidence:to:delight"));
  eventBus.subscribe("app:init", () => fresh["system-status"].transition("app:init"));
  eventBus.subscribe("app:loaded", () => fresh["system-status"].transition("app:loaded"));
  eventBus.subscribe("system:loadFailed", () => fresh["system-status"].transition("system:loadFailed"));
  eventBus.subscribe("system:retry", () => fresh["system-status"].transition("system:retry"));
  eventBus.subscribe("interaction:userApproach", () => fresh["interaction-phase"].transition("interaction:userApproach"));
  eventBus.subscribe("interaction:userInput", () => fresh["interaction-phase"].transition("interaction:userInput"));
  eventBus.subscribe("interaction:actionComplete", () => fresh["interaction-phase"].transition("interaction:actionComplete"));
  eventBus.subscribe("interaction:settle", () => fresh["interaction-phase"].transition("interaction:settle"));
  eventBus.subscribe("interaction:nextInput", () => fresh["interaction-phase"].transition("interaction:nextInput"));
}

export interface ComponentSpec {
  name: string;
  responsibility: string;
}

export const components: ComponentSpec[] = [
  { name: "AppShell", responsibility: "Root layout, global state providers, motion engine provider" },
  { name: "EntrySequence", responsibility: "Hook: The first pixel you see should make you pause." },
  { name: "MainContent", responsibility: "Primary content area based on approved experience" },
  { name: "FeedbackLayer", responsibility: "Renders visual/audio feedback for all user interactions" },
  { name: "AmbientMotionLayer", responsibility: "Background animations, parallax, particle effects" },
];

export const performanceBudget = {
  loadTime: "2s",
  timeToInteractive: "3.5s",
  frameRate: "60fps",
  bundleSize: "250KB",
  firstMeaningfulPaint: "1.5s",
};

export interface QualityGateSpec {
  id: string;
  description: string;
  dimension: string;
  passCondition: string;
}

export const qualityGates: QualityGateSpec[] = [
  { id: "QG-001", description: "All state machines defined and wired", dimension: "reliability", passCondition: "No unhandled state transitions" },
  { id: "QG-002", description: "Motion matches approved easing and duration", dimension: "experience", passCondition: "CSS/JS motion values match compiler output" },
  { id: "QG-003", description: "Users feel a sense of discovery within 10 seconds", dimension: "experience", passCondition: "Verified through user testing: Users feel a sense of discovery within 10 seconds" },
  { id: "QG-004", description: "Users complete their primary task without confusion", dimension: "experience", passCondition: "Verified through user testing: Users complete their primary task without confusion" },
  { id: "QG-005", description: "Users want to return tomorrow", dimension: "experience", passCondition: "Verified through user testing: Users want to return tomorrow" },
];

export interface InstrumentationSpec {
  event: string;
  trigger: string;
  metric: string;
}

export const instrumentation: InstrumentationSpec[] = [
  { event: "app:load", trigger: "Application ready", metric: "loadTime" },
  { event: "metric:timeToFirstInteraction", trigger: "Time to first interaction", metric: "< 3s" },
  { event: "metric:userCanRecall3FeaturesAfterFir", trigger: "User can recall 3 features after first visit", metric: "> 70% in testing" },
  { event: "emotion:curiosity:to:discovery", trigger: "First interaction reveals unexpected detail", metric: "transitionTime" },
  { event: "emotion:discovery:to:confidence", trigger: "Pattern becomes clear and predictable", metric: "transitionTime" },
  { event: "emotion:confidence:to:delight", trigger: "Polished micro-interaction exceeds expectation", metric: "transitionTime" },
];

export function verifyArchitecture(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  for (const machine of Object.values(machines)) {
    if (!machine.states.includes(machine.getState())) {
      errors.push(`State machine "${machine.name}": initial state is not declared`);
    }
    for (const rule of machine.transitions) {
      if (!machine.states.includes(rule.from)) {
        errors.push(`State machine "${machine.name}": transition from "${rule.from}" is not a declared state`);
      }
      if (!machine.states.includes(rule.to)) {
        errors.push(`State machine "${machine.name}": transition to "${rule.to}" is not a declared state`);
      }
    }
  }
  if (components.length === 0) {
    errors.push('No components declared');
  }
  if (qualityGates.length === 0) {
    errors.push('No quality gates declared');
  }
  return { valid: errors.length === 0, errors };
}
