import { execSync } from 'child_process';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { EngineeringArchitecture } from './experience-compiler.js';
import { AuditTrail } from '../audit-trail.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');

export interface ImplementationResult {
  generatedFiles: string[];
  compilePassed: boolean;
  testPassed: boolean;
  auditIds: string[];
  success: boolean;
}

const RUNTIME_TEMPLATE = `// Generated by Governance Pipeline
// Implementation has NO access to original requirements
// Architecture version: {{VERSION}}

export interface AppEvent {
  name: string;
  payload: unknown;
  timestamp: number;
}

export type EventHandler = (event: AppEvent) => void;

export class EventBus {
  private readonly listeners = new Map<string, EventHandler[]>();

  subscribe(event: string, handler: EventHandler): () => void {
    const handlers = this.listeners.get(event) ?? [];
    handlers.push(handler);
    this.listeners.set(event, handlers);
    return () => {
      const current = this.listeners.get(event);
      if (current === undefined) return;
      const index = current.indexOf(handler);
      if (index >= 0) current.splice(index, 1);
    };
  }

  emit(name: string, payload: unknown = {}): void {
    const event: AppEvent = { name, payload, timestamp: Date.now() };
    for (const handler of this.listeners.get(name) ?? []) {
      handler(event);
    }
  }

  listenerCount(name: string): number {
    return (this.listeners.get(name) ?? []).length;
  }
}

export class IllegalTransitionError extends Error {
  constructor(machine: string, state: string, event: string) {
    super(\`State machine "\${machine}": no transition from "\${state}" on event "\${event}"\`);
    this.name = 'IllegalTransitionError';
  }
}

export interface TransitionRule {
  from: string;
  to: string;
  on: string;
}

export class StateMachine {
  readonly name: string;
  readonly states: readonly string[];
  readonly transitions: readonly TransitionRule[];
  private currentState: string;

  constructor(name: string, states: string[], initialState: string, transitions: TransitionRule[]) {
    this.name = name;
    this.states = states;
    this.currentState = initialState;
    this.transitions = transitions;
  }

  getState(): string {
    return this.currentState;
  }

  can(event: string): boolean {
    return this.transitions.some(t => t.from === this.currentState && t.on === event);
  }

  transition(event: string): string {
    const rule = this.transitions.find(t => t.from === this.currentState && t.on === event);
    if (rule === undefined) {
      throw new IllegalTransitionError(this.name, this.currentState, event);
    }
    this.currentState = rule.to;
    return this.currentState;
  }
}

export const eventBus = new EventBus();

export function createMachines(): Record<string, StateMachine> {
  return {
{{MACHINES}}
  };
}

export const machines = createMachines();

export function wireDefaultHandlers(): void {
  const fresh = createMachines();
{{WIRING}}
}

export interface ComponentSpec {
  name: string;
  responsibility: string;
}

export const components: ComponentSpec[] = [
{{COMPONENTS}}
];

export const performanceBudget = {
{{PERFORMANCE}}
};

export interface QualityGateSpec {
  id: string;
  description: string;
  dimension: string;
  passCondition: string;
}

export const qualityGates: QualityGateSpec[] = [
{{QUALITY_GATES}}
];

export interface InstrumentationSpec {
  event: string;
  trigger: string;
  metric: string;
}

export const instrumentation: InstrumentationSpec[] = [
{{INSTRUMENTATION}}
];

export function verifyArchitecture(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  for (const machine of Object.values(machines)) {
    if (!machine.states.includes(machine.getState())) {
      errors.push(\`State machine "\${machine.name}": initial state is not declared\`);
    }
    for (const rule of machine.transitions) {
      if (!machine.states.includes(rule.from)) {
        errors.push(\`State machine "\${machine.name}": transition from "\${rule.from}" is not a declared state\`);
      }
      if (!machine.states.includes(rule.to)) {
        errors.push(\`State machine "\${machine.name}": transition to "\${rule.to}" is not a declared state\`);
      }
    }
  }
  if (components.length === 0) {
    errors.push('No components declared');
  }
  if (qualityGates.length === 0) {
    errors.push('No quality gates declared');
  }
  return { valid: errors.length === 0, errors };
}
`;

function emitMachines(arch: EngineeringArchitecture): string {
  return arch.stateMachines
    .map(sm => {
      const transitions = sm.transitions
        .map(t => `    { from: ${JSON.stringify(t.from)}, to: ${JSON.stringify(t.to)}, on: ${JSON.stringify(t.on)} }`)
        .join(',\n');
      return (
        `    ${JSON.stringify(sm.name)}: new StateMachine(\n` +
        `      ${JSON.stringify(sm.name)},\n` +
        `      ${JSON.stringify(sm.states)},\n` +
        `      ${JSON.stringify(sm.initialState)},\n` +
        `      [\n${transitions}\n      ],\n` +
        `    ),`
      );
    })
    .join('\n');
}

function emitWiring(arch: EngineeringArchitecture): string {
  const lines: string[] = [];
  let index = 0;
  for (const sm of arch.stateMachines) {
    for (const t of sm.transitions) {
      lines.push(
        `  eventBus.subscribe(${JSON.stringify(t.on)}, () => fresh[${JSON.stringify(sm.name)}].transition(${JSON.stringify(t.on)}));`,
      );
      index++;
    }
  }
  if (lines.length === 0) {
    lines.push('  // no transitions to wire');
  }
  return lines.join('\n');
}

function emitComponents(arch: EngineeringArchitecture): string {
  return arch.components
    .map(
      c =>
        `  { name: ${JSON.stringify(c.name)}, responsibility: ${JSON.stringify(c.responsibility)} },`,
    )
    .join('\n');
}

function emitPerformance(arch: EngineeringArchitecture): string {
  const p = arch.performance;
  return [
    `  loadTime: ${JSON.stringify(p.loadTime)},`,
    `  timeToInteractive: ${JSON.stringify(p.timeToInteractive)},`,
    `  frameRate: ${JSON.stringify(p.frameRate)},`,
    `  bundleSize: ${JSON.stringify(p.bundleSize)},`,
    `  firstMeaningfulPaint: ${JSON.stringify(p.firstMeaningfulPaint)},`,
  ].join('\n');
}

function emitQualityGates(arch: EngineeringArchitecture): string {
  return arch.qualityGates
    .map(
      g =>
        `  { id: ${JSON.stringify(g.id)}, description: ${JSON.stringify(g.description)}, dimension: ${JSON.stringify(g.dimension)}, passCondition: ${JSON.stringify(g.passCondition)} },`,
    )
    .join('\n');
}

function emitInstrumentation(arch: EngineeringArchitecture): string {
  return arch.instrumentation
    .map(
      i =>
        `  { event: ${JSON.stringify(i.event)}, trigger: ${JSON.stringify(i.trigger)}, metric: ${JSON.stringify(i.metric)} },`,
    )
    .join('\n');
}

function buildImplementation(arch: EngineeringArchitecture, version: string): string {
  return RUNTIME_TEMPLATE
    .replace('{{VERSION}}', version)
    .replace('{{MACHINES}}', emitMachines(arch))
    .replace('{{WIRING}}', emitWiring(arch))
    .replace('{{COMPONENTS}}', emitComponents(arch))
    .replace('{{PERFORMANCE}}', emitPerformance(arch))
    .replace('{{QUALITY_GATES}}', emitQualityGates(arch))
    .replace('{{INSTRUMENTATION}}', emitInstrumentation(arch));
}

function buildImplementationTest(arch: EngineeringArchitecture): string {
  const sections: string[] = [];

  sections.push(
    `// Tests driven by Engineering Architecture
// Quality gates: ${arch.qualityGates.map(g => g.id).join(', ')}
import { describe, it, expect } from 'vitest';
import {
  EventBus,
  IllegalTransitionError,
  StateMachine,
  createMachines,
  eventBus,
  wireDefaultHandlers,
  components,
  performanceBudget,
  qualityGates,
  verifyArchitecture,
} from './implementation.js';
`,
  );

  sections.push(`describe('Generated implementation — architecture-driven', () => {
  it('exposes ${arch.stateMachines.length} state machines', () => {
    expect(Object.keys(createMachines()).length).toBe(${arch.stateMachines.length});
  });
`);

  for (const sm of arch.stateMachines) {
    sections.push(`
  it('machine ${JSON.stringify(sm.name)} starts in ${JSON.stringify(sm.initialState)}', () => {
    const machine = createMachines()[${JSON.stringify(sm.name)}];
    expect(machine.getState()).toBe(${JSON.stringify(sm.initialState)});
  });
`);
    if (sm.transitions.length > 0) {
      const t = sm.transitions[0];
      sections.push(`
  it('machine ${JSON.stringify(sm.name)} follows a legal transition', () => {
    const machine = createMachines()[${JSON.stringify(sm.name)}];
    const rule = machine.transitions[0];
    expect(machine.can(rule.on)).toBe(true);
    expect(machine.transition(rule.on)).toBe(rule.to);
  });
`);
      sections.push(`
  it('machine ${JSON.stringify(sm.name)} rejects an illegal event', () => {
    const machine = createMachines()[${JSON.stringify(sm.name)}];
    expect(() => machine.transition('__never_emitted__')).toThrow(IllegalTransitionError);
  });
`);
    }
  }

  sections.push(`
  it('event bus delivers events to subscribers', () => {
    const bus = new EventBus();
    let received = 0;
    bus.subscribe('test:event', () => {
      received += 1;
    });
    bus.emit('test:event');
    expect(received).toBe(1);
  });

  it('default handlers wire without errors', () => {
    expect(() => wireDefaultHandlers()).not.toThrow();
    expect(eventBus.listenerCount('app:init')).toBeGreaterThan(0);
  });

  it('declares ${arch.components.length} components including AppShell', () => {
    expect(components.length).toBe(${arch.components.length});
    expect(components.some(c => c.name === 'AppShell')).toBe(true);
  });

  it('declares ${arch.qualityGates.length} quality gates', () => {
    expect(qualityGates.length).toBe(${arch.qualityGates.length});
  });

  it('performance budget is defined', () => {
    expect(performanceBudget.loadTime).toBe(${JSON.stringify(arch.performance.loadTime)});
    expect(performanceBudget.bundleSize).toBe(${JSON.stringify(arch.performance.bundleSize)});
  });

  it('architecture verifies without errors', () => {
    const result = verifyArchitecture();
    expect(result.valid).toBe(true);
    expect(result.errors).toEqual([]);
  });
});
`);

  return sections.join('\n');
}

export class ImplementationEngine {
  readonly #hasRequirements = false;

  getRequirementsAccess(): boolean {
    return this.#hasRequirements;
  }

  execute(
    arch: EngineeringArchitecture,
    projectDir: string,
    auditTrail: AuditTrail,
  ): ImplementationResult {
    const generatedFiles: string[] = [];
    const auditIds: string[] = [];

    const generatedDir = join(ROOT, projectDir);
    if (!existsSync(generatedDir)) {
      mkdirSync(generatedDir, { recursive: true });
    }

    const implContent = buildImplementation(arch, auditTrail.getVersion());
    const implPath = join(generatedDir, 'implementation.ts');
    writeFileSync(implPath, implContent, 'utf-8');
    generatedFiles.push(implPath);

    const testContent = buildImplementationTest(arch);
    const testPath = join(generatedDir, 'implementation.test.ts');
    writeFileSync(testPath, testContent, 'utf-8');
    generatedFiles.push(testPath);

    let compilePassed = false;
    let testPassed = false;

    try {
      execSync(
        `npx tsc --noEmit --strict --esModuleInterop --moduleResolution bundler --module ESNext --target ES2022 "${implPath}" 2>&1`,
        { cwd: ROOT, timeout: 15000, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] },
      );
      compilePassed = true;
    } catch {
      compilePassed = false;
    }

    try {
      execSync(
        `npx vitest run "${testPath}" --reporter verbose 2>&1`,
        { cwd: ROOT, timeout: 15000, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] },
      );
      testPassed = true;
    } catch {
      testPassed = false;
    }

    for (const file of generatedFiles) {
      const approvalChain = ['experience-architecture', 'engineering-architecture', 'implementation'];
      const auditId = auditTrail.writeArtifact(
        'implementation',
        file.replace(/^.*[\\/]/, '') + '.audit.json',
        { architectureVersion: auditTrail.getVersion(), compilePassed, testPassed },
        projectDir,
        approvalChain,
      );
      auditIds.push(auditId);
    }

    return {
      generatedFiles,
      compilePassed,
      testPassed,
      auditIds,
      success: compilePassed && testPassed,
    };
  }
}
